### ISSUE TITLE
[Feature request] Move to the selected directory on exit

### ISSUE THREAD

**Issue by walking-octopus** [souvikinator/lsx#25]

**Comment by wlwww16** [comment]
It does this already, that's how the application works. Run the script, navigate to the desired directory, then CTRL+C to exit, and you will be there.

**Comment by souvikinator** [comment]
@wlwww16 thanks for answering. 
@walking-octopus closing the issue for now, in case you face any problem feel free to reopen.

**Comment by dreamcat4** [comment]
installed your tool today with `go install github.com/souvikinator`. Because `go install` is the official go ways of installing tools. (so no install.sh)...

and it is broke that way for me. It does not change folder after ctrl+c exit. So clearly there are some user deployed situations whereby it's failing to work. Maybe because the shell is a parent process, right?

This also makes me wonder if you are using VTE api interface. Or something more custom to tell the parent shell what folder to cd into

**Comment by souvikinator** [comment]
Yes you are right about installation but it only installs the executable (`ls-x`) which is in turn used by a shell function (`lsx`) to make `cd` possible. `install.sh` builds from source and also sets up wrapper functions and files for it to work. So in short `install.sh` is doing more than just `go install`.
No, I'm not using VTE API.  As the program exits, I simply write the target directory to file and then cd to that target directory using the wrapped function.
