### ISSUE TITLE
ability to set file browsing to use the entire terminal window 

### ISSUE THREAD

**Issue by ThorCrowley** [souvikinator/lsx#26]
Thanks for the great program !
It would be neat if there would be an option to use the entire terminal window for browsing or just make this default.
Maybe I am overlooking something but it seems to be wasting terminal space by using only the upper part.
Just a thought :)

**Comment by souvikinator** [comment]
Hey, thanks! Glad you liked it :)
Yes, I agree with that. I was in fact working on revamping the UI a little bit but felt like I was over-engineering and no one asked for it so I dropped it.
So yeah have to add it back to the to-do list. Thanks for the feedback.

**Comment by dreamcat4** [comment]
installed your tool today with `go install github.com/souvikinator`. Because `go install` is the official go ways of installing tools. (so no install.sh)...

and it is broke that way for me. It does not change folder after ctrl+c exit. So clearly there are some user deployed situations whereby it's failing to work. Maybe because the shell is a parent process, right?

This also makes me wonder if you are using VTE api interface. Or something more custom to tell the parent shell what folder to cd into

**Comment by souvikinator** [comment]
This issue is addressed in the latest release (v0.1.9)
